services:
  - type: web
    name: tanzamart
    env: docker
    plan: free
    region: frankfurt
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: TanzaMart
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: DB_CONNECTION
        value: sqlite
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
